export const assets = {
    logo: '/assets/logo.svg',
    search_icon: '/assets/search_icon.svg',
    sketch: '/assets/sktech.svg',
    microsoft_logo: '/assets/microsoft_logo.svg',
    walmart_logo: '/assets/walmart_logo.svg',
    accenture_logo: '/assets/accenture_logo.svg',
    adobe_logo: '/assets/adobe_logo.svg',
    paypal_logo: '/assets/paypal_logo.svg',
    course_1_thumbnail: '/assets/course_1.png',
    course_2_thumbnail: '/assets/course_2.png',
    course_3_thumbnail: '/assets/course_3.png',
    course_4_thumbnail: '/assets/course_4.png',
    star: '/assets/rating_star.svg',
    star_blank: '/assets/star_dull_icon.svg',
    profile_img_1: '/assets/profile_img_1.png',
    profile_img_2: '/assets/profile_img_2.png',
    profile_img_3: '/assets/profile_img_3.png',
    arrow_icon: '/assets/arrow_icon.svg',
    dropdown_icon: '/assets/dropdown_icon.svg',
    cross_icon: '/assets/cross_icon.svg',
    upload_area: '/assets/upload_area.svg',
    logo_dark: '/assets/logo_dark.svg',
    down_arrow_icon: '/assets/down_arrow_icon.svg',
    time_left_clock_icon: '/assets/time_left_clock_icon.svg',
    time_clock_icon: '/assets/time_clock_icon.svg',
    user_icon: '/assets/user_icon.svg',
    home_icon: '/assets/home_icon.svg',
    add_icon: '/assets/add_icon.svg',
    my_course_icon: '/assets/my_course_icon.svg',
    person_tick_icon: '/assets/person_tick_icon.svg',
    facebook_icon: '/assets/facebook_icon.svg',
    instagram_icon: '/assets/instagram_icon.svg',
    twitter_icon: '/assets/twitter_icon.svg',
    course_4: '/assets/course_4.png',
    file_upload_icon: '/assets/file_upload_icon.svg',
    appointments_icon: '/assets/appointments_icon.svg',
    earning_icon: '/assets/earning_icon.svg',
    patients_icon: '/assets/patients_icon.svg',
    profile_img: '/assets/profile_img.png',
    profile_img2: '/assets/profile_img2.png',
    profile_img3: '/assets/profile_img3.png',
    play_icon: '/assets/play_icon.svg',
    blue_tick_icon: '/assets/blue_tick_icon.svg',
    lesson_icon: '/assets/lesson_icon.svg'
}

export const dummyTestimonial = [
    {
        name: 'Donald Jackman',
        role: 'SWE 1 @ Amazon',
        image: assets.profile_img_1,
        rating: 5,
        feedback: 'I\'ve been using Imagify for nearly two years, primarily for Instagram, and it has been incredibly user-friendly, making my work much easier.',
    },
    {
        name: 'Richard Nelson',
        role: 'SWE 2 @ Samsung',
        image: assets.profile_img_2,
        rating: 4,
        feedback: 'I\'ve been using Imagify for nearly two years, primarily for Instagram, and it has been incredibly user-friendly, making my work much easier.',
    },
    {
        name: 'James Washington',
        role: 'SWE 2 @ Google',
        image: assets.profile_img_3,
        rating: 4.5,
        feedback: 'I\'ve been using Imagify for nearly two years, primarily for Instagram, and it has been incredibly user-friendly, making my work much easier.',
    },
];
